<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
        <PackageReference Include="NetArchTest.Rules" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="../SC.Api/SC.Api.csproj" />
      <ProjectReference Include="../SC.Application/SC.Application.csproj" />
      <ProjectReference Include="../SC.Contract/SC.Contract.csproj" />
      <ProjectReference Include="../SC.Domain/SC.Domain.csproj" />
      <ProjectReference Include="../SC.Infrastructure/SC.Infrastructure.csproj" />
      <ProjectReference Include="../SC.Persistence/SC.Persistence.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
    </ItemGroup>

</Project>